version : '3'

services:
  adminer:
    image: adminer
    ports:
    - 8080:8080
    networks:
      - mynet
      - mynet1
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynet2
  storeDatabase:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
      - 4000:3308
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - dbdatastore:/var/lib/mysql
    networks:
      - mynet
      - mynet1
  storeDatabaseMigration:
      image: storedatabasemigration
      environment:
        - DATABASE_URL=storeDatabase
        - REDIS=redis
      depends_on:
        storeDatabase:
          condition: service_healthy
      networks:
      - mynet
      - mynet1
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 4001:3308
    volumes:
      - dbdatausers:/var/lib/mysql
    networks:
      - mynet
  authenticationDatabaseMigration:
      image: authenticationdatabasemigration
      environment:
        - DATABASE_URL=authenticationDatabase
      depends_on:
        authenticationDatabase:
          condition: service_healthy
      networks:
      - mynet
  authentication:
    image: authentication
    ports:
    - 5000:5000
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - mynet
  customer:
    image: customer
    ports:
    - 5001:5001
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS=redis
    networks:
      - mynet1
  warehouse:
    image: warehouse
    ports:
      - 5002:5002
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS=redis
    networks:
      - mynet2
  admin:
    image: admin
    ports:
      - 5003:5003
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS=redis
    networks:
      - mynet1
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS=redis
    networks:
      - mynet1
      - mynet2
volumes:
  dbdatastore:
  dbdatausers:
networks:
  mynet:
  mynet1:
  mynet2: